version: 2
sources:
  - name: staging
    database: "{{ env_var('GCP_PROJECT') }}"
    schema: trips_data_all
    tables:
      - name: tree-report-partitioned-clustered 
        description: "Public trees dataset partitioned and clustered"
   